# Generated by Django 4.0.4 on 2022-04-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_value', models.CharField(max_length=50)),
                ('second_value', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=30)),
            ],
        ),
    ]
